dist: xenial
services:
- docker
language: go
env:
  global:
  - GO111MODULE=on
  - secure: HKz4VaSzJCibZich61TcUjnkxkakUeJAtlMI+9dPnvbWaovYrUYSCySxUwKMWwM8y8nJ0QZF3kIuaSR1Wr4z6bNKWkhaDWiZH7nOlXD5R4hDgMoU9jb9urC7hrl66pR6ZTjXWvLzhpmrzI4usk9AORy9oySfMijJONsmq4k8f6w8kW9i/uxs1SExBfFNxnzk4zaKS9x2YV3EQeshmZou12pBZf5qaFAhRPUvivYAHUJKGaRLTEfHicWKIhlEpGew3CDhkvUzFJgAodWId+OfN73XJoapjzuPEvGEeBHKUGVngCCM8YkGs0eZebCNrvk8YMbVZf7jDdmMe36alMY+qmbhKD7v5btfCD+lmJcS7q++KlsP0phXmIUgNVQWaxDWW2JU3H6goKy4YcCPTuIBiMzm+S3jvCU1z1d//vh3UX2kiVy/2r7YceMv7DkshkFgIEdTE4+9WHrGT+8FsV9q2F6rwAwss0g3M2fToTMUg7puD7A1T7k+thB6G3vS85swLJRF9Vt6TwXjoIT0hFHR4dWYc2oreR7uI/CnCY1Qh0VLjJ8HYCdRqgoPYSdaJxkyPMOQQE9bPnKswAFoogq/3czbTJSF1J9FUcbRMYwOrjfgAWCxAEhcQq77W+2Mm3JDzfwUhEKg61KKxjqekYbbtY/+yOTmDnhieWXa0gtDg0g=
  - secure: ku3PYqzDtERaoGGHPeZukYPdzvoUvpr8pyjSN7lM3oDEf7bspyF2Qxy+xHPgG1esqtaRuw82pbMsp5MZ0PoOtMMVvpU6drUgjFYGO0q+L6fSiD2tgRuyPeSkslxHP0TIQYdWarLHDDUN2uUUUVwFvlWWVKmf/SC+N/rkLmuUKaSDa5xKDIoytfZUFZcu3XpLDPXlMxJAeHBkmZ81C4uXfGxWK+bmaq4UY373vV2xYSXalKWSauiZ5+KgwEEBdEUY0aKKB/zGZ+ddlZB6OgqCurfQmvcfR4GZoA4mue9/PgmmjNGInSZXw9COlsm0W8NCbds/K7ZNdXKAiw/UhOS5UdbFixr45SvHd6D7EWm1fjOgNos9H1Z8zM9GKq5gXKIUn3zExL3SWAIjgRlrbAe2ar2wLY85Gj//8e4s/RGdhstBwe7siEpmpuwy5KJKB7wSrOvNeI9d75AT0HkDTUnIzV96vOf9mIO6pvcvC9kv5YeL2icL0aisbfkAdXrPWJBgdPcv4v0TP8rIltD+DvC81K2586uqgRGjCijMfxBmKFs+UEbWZBi6MHcLn0Megr1/g3YJyXj0txPudKrpgQO7l63oQb0k6BaFlePxcTc9GlCcD2Y+kURxjnVn6BxMMqnX3iwvuoKKHtH6quvqXypoQrv6oNCfFUKaBgr2Q/xMFS4=
  - secure: zFkviV5PcjQnopx/aaY5z0rFZZUZtmxMIpnmm9CsHPr/HHcIjC0Z3CCVBKtNyvCTTNO/ly4niMM2KTyAApdZIlomRgsyTZk3FKAWq+teAVKXq+sR6NpMN4EcEPlBaO5sfpC97ps82//KhBB0S50tJqrmElsrJepps60pfZkTtAcd+Kgv4od7CX7IKD64o3Cwrc5KnvzMvzXGkbdgZJobqwctee5e3VHo22qmhyV5dv/dDHOlCTQJWd7QMfeYdTRhKevzSq6akRu9ynFs0QooMBNcNF9fcjdmecBfxbeNgx7u0kPJlt/ay8H5JImiYM2mXEKyAxT3gzMKjagJyVAseorwXIbpuYzP24hHHm52bz4Q7WnOZ/vnh+DE5wFUMZK+cdNAio2H3yRXwy3xXUZ/nnb2Zxz/5I1xnFZgZADyJSJ42CA9Ax65BlHgsveQcIofRPnclWgCiM5Sc5WLzuXhADdwdIusn71teG4b8h2tXm0aM1cAjDVZmuawY3mrP3l6ok//KS1F4rRXI1p4Io2msvZ3Zmk7NnR9le1wPWB35Rr3hWesPxTqb79KLbudZ+QMonbU3RVkZ+31W9IRS/B7yIf00ytdJbcNVoY1FHb4bHiX3J13tEBONnSWv/lXpzX8gsRrDAcXx9zisE2IE+DQxflQHlVbG4GtLHi/SnGEyOQ=
  - secure: BsqKUo7HYtXTZgwbOLdgz7OcNeaynJqxRini6Y/GnuFFgiJB6MSuUbdTUWddxRYoFJlt6lVRsAkzPDB8JG+/4WLtK0FspsGHpJGhD0MTTUdIaygJ4HPiFKrTl743X+elN59OkZq9bLFx+jQMTCMUm4ZVt+zg3xAJ4O9cktpyTcaqrAXQomPGjB6nTyj5cJ3Lmaswe1axeNPSxIakfR5F/VEid5QnqnADCCL8bqVvypH9q38xnGDC9ctX4vu9LXLOSBy7GkVO60pFFbEEA3OiNgFrrZtDvUjseGGYhfSOWfwhIxb8MhIo6Wwh1udGotDOrWBQq4jDXysLGgcOR1Fu6oEXA8inqwM4sgtaMSfZk3k81vTRnd9ZJHUwJ3XBJk4uvFtRqLBh0DvR3JrKpMvxunu+FOyGpxo8G9+eoAoOgE2e/QREoFHVxb/kjNST3o2abRtZYxCdW3GC5npRbXTMSoCcKMJFK6pHfSrSfreBMcKPcvqO8jUMiXS5lNZEaCgEsmpyTYiN85m8AihOtUj6UKdsWihJVk7dUCKGeQ16rIKIL11sDTQC9YQcd5/Jl6Wb/8teYD3fvguml5tluiiyvDhsWBdT3hrf7XkyszPGeWt5i9GxXYsg5AAGdw5Xemshww8wDewiK0wCwlmTJ2k4JGy3ohYMepp1E6rDjNZ866A=
go:
- 1.12.1
install: true

before_script:
- go get -u golang.org/x/lint/golint
script:
- golint ./...
- make test

before_deploy:
- docker login --username=_ --password=$HEROKU_TOKEN registry.heroku.com
deploy:
- provider: script
  script: make release
  on:
    branch: master
notifications:
  email: false
