dist: xenial
language: go
env:
  global:
    - GO111MODULE=on
    - secure: oSb7dHqjadJ59kYxsh2Xorxv/JXxGHy4BgZmZ1qFrvHGjFe449dfFl7lpkgG0DJYeqAqyRvgEC1C4yJX7NUYkNO7LcMym64pIL2WfdTec77j8XVYmdBK9fgdHoZqzNY3KZICLoGTWnw5neYnKLEsm1tDvH+rl82qTO1hJOwA37X4qBCe5j/KrrcUxzJpHnrWAG+ZvjI5bIT7A38E1iwknag3INrPhoXKLVr8lUQ4TRI8okbdLsWgQIxfYNvDvUSwHp1aZIWLLattkYVQpZg9ATrK+gR2Kh12cvVbnECijHRRorBLLLJFzx5lfH6uRD+QZAYv+pA9eNacYcGzczXyfeW5rc/42q9Ac6DGm604x/ExUfYeAzIEE8A02XKfQ8jjXgsHBq2PPmF0njyLXTywPMjCUkS9lQMOwDilfxuDzKYXPgWSaN8YyPsuhN9Z3LGGMTQZykWoBq3D4nZfJ7GzadPzveM9462V1ytZXs2YALpBb1p1huiIGJ/mCErZcSxFztQjRxxKXpnLdYSJ1OyLeRq0Z9HzdVMbApEpLlUkDUSRICbEXzztWkJYtzgDeV8WewNR81lEJQFzdQVjM9jRE/c3pxqsvfDRpfJGHplgfWNgndlrWgZfpciLL7h3gyfKfwTpQzVZa0Kb13CyDDN41CHJx4dnfpK/L+yCGmSJA/U=
go:
- 1.12.1
install: true
notifications:
  email: false
before_script:
  - go get -u golang.org/x/lint/golint
script:
- golint ./...
- go test -v ./...
