steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/animal-api-img:$REVISION_ID", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/animal-api-img:$REVISION_ID"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "app",
        "deploy",
        "--image-url",
        "gcr.io/$PROJECT_ID/animal-api-img:$REVISION_ID",
      ]
    secretEnv: ["DOG_API_KEY"]
timeout: "1600s"
secrets:
  - kmsKeyName: projects/$PROJECT_ID/locations/global/keyRings/ANIMAL_KEYRING/cryptoKeys/ANIMAL_KEY
    secretEnv:
      DOG_API_KEY: CiQAfPwswo1eYUPRocVQ6P5lXDXy+dBfWLo/N6M85XVKg6Zagj0STQDm+mqhk4rrREHyxhryNsAFE7fGMwC67WQ7C5DzCHfMqo/BU52PdFlfTqDrCpEVy/nAhMKoyeFan8eNbHrQtlIaxOb8pQrjkIEMJQVd
