steps:
- name: "gcr.io/cloud-builders/go"
  args: ["test", "-coverprofile=coverage.out", "./..."]
  env: ["PROJECT_ROOT=https://github.com/maria-robobug/animal-api", "GO111MODULE=on"]
- name: "gcr.io/cloud-builders/go"
  args: ["build", "-o", "bin/animal-api", "."] 
  env: ["PROJECT_ROOT=https://github.com/maria-robobug/animal-api", "GO111MODULE=on", "GOOS=linux", "GOARCH=amd64"]
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/animal-api-img:$REVISION_ID", "."]
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/animal-api-img:$REVISION_ID"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "--image-url", "gcr.io/$PROJECT_ID/animal-api-img:$REVISION_ID"]
timeout: "1600s"
