steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/animal-api-img:$REVISION_ID", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/animal-api-img:$REVISION_ID"]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "app",
        "deploy",
        "--image-url",
        "gcr.io/$PROJECT_ID/animal-api-img:$REVISION_ID",
      ]
timeout: "1600s"
